using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Wholphin.Engine.Data.Entities;

namespace Wholphin.Engine.Metadata;

/// <summary>
/// Produces a spoiler-free, safety-first-ordered set of content advisories for a title, generated by
/// the configured LLM (Groq) from the title's overview/metadata. Results are cached in-memory and
/// persisted durably on the catalog row — one set per movie/series, never per episode. Groq is the
/// sole source: when it is unavailable the result is "no warnings" (never invented).
/// </summary>
public interface IContentWarningProvider
{
    /// <summary>Returns the content advisories for a title (empty when none / unconfigured).</summary>
    /// <param name="item">The catalog item (a movie or a series).</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The advisory set.</returns>
    Task<ContentWarnings> GetAsync(CatalogItem item, CancellationToken ct = default);
}

/// <summary>A single content advisory.</summary>
public class ContentWarning
{
    /// <summary>Gets or sets the category (one of <see cref="ContentWarningCategories.Ordered"/>).</summary>
    public string Category { get; set; } = string.Empty;

    /// <summary>Gets or sets the severity: mild, moderate, or severe.</summary>
    public string Severity { get; set; } = "moderate";

    /// <summary>Gets or sets a short, spoiler-free description of the kind of content.</summary>
    public string Note { get; set; } = string.Empty;
}

/// <summary>The full advisory set for a title.</summary>
public class ContentWarnings
{
    /// <summary>Gets or sets a value indicating whether any advisories apply.</summary>
    public bool HasWarnings { get; set; }

    /// <summary>Gets or sets a one-line plain-language summary.</summary>
    public string Summary { get; set; } = string.Empty;

    /// <summary>Gets or sets the advisories, in fixed safety-first order.</summary>
    public List<ContentWarning> Warnings { get; set; } = new();

    /// <summary>Gets an empty advisory set.</summary>
    public static ContentWarnings None => new() { HasWarnings = false };
}

/// <summary>The fixed advisory categories and their canonical order (health and trauma first, language last).</summary>
public static class ContentWarningCategories
{
    /// <summary>The allowed categories in their canonical display/sort order.</summary>
    public static readonly IReadOnlyList<string> Ordered = new[]
    {
        "Photosensitivity",
        "Suicide and self-harm",
        "Sexual violence",
        "Harm to children",
        "Animal cruelty",
        "Graphic violence and gore",
        "Death, grief and medical trauma",
        "Sexual content and nudity",
        "Substance use and addiction",
        "Disturbing and frightening imagery",
        "Strong language and slurs",
        "Other sensitive themes",
    };

    /// <summary>Returns the canonical sort index of a category (or <see cref="int.MaxValue"/> when unknown).</summary>
    /// <param name="category">The category name (case-insensitive).</param>
    /// <returns>The 0-based order index, or int.MaxValue when not a known category.</returns>
    public static int OrderOf(string? category)
    {
        for (var i = 0; i < Ordered.Count; i++)
        {
            if (string.Equals(Ordered[i], category, StringComparison.OrdinalIgnoreCase))
            {
                return i;
            }
        }

        return int.MaxValue;
    }
}
